variables:
  GIT_SUBMODULE_STRATEGY: recursive

image:
    name: ghcr.io/kos-builds/kos-dc:latest-14.1.0
    entrypoint: ["/bin/sh",  "-c", 'echo gitlab command: "$@" && /bin/bash -c "$@"'] 

build-dreamcast-liberty:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y ccache
    - update-ccache-symlinks
    - rm -rf /opt/toolchains/dc/kos
    - cp -R vendor/dca3-kos /opt/toolchains/dc/kos
    - make -C /opt/toolchains/dc/kos/kernel/arch/dreamcast/sound/arm
    - make -C /opt/toolchains/dc/kos -j $(nproc)
  script:
    - cd liberty
    - make -j $(nproc)
  artifacts:
    paths:
      - liberty/dca-liberty.elf

build-dreamcast-miami:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y ccache
    - update-ccache-symlinks
    - rm -rf /opt/toolchains/dc/kos
    - cp -R vendor/dca3-kos /opt/toolchains/dc/kos
    - make -C /opt/toolchains/dc/kos/kernel/arch/dreamcast/sound/arm
    - make -C /opt/toolchains/dc/kos -j $(nproc)
  script:
    - cd miami
    - make -j $(nproc)
  artifacts:
    paths:
      - miami/dca-liberty.elf

build-texconv-liberty:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential gcc g++ ccache
    - update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:$PATH"
    - cd liberty
    - make texconv -j $(nproc)
  artifacts:
    paths:
      - liberty/texconv

build-texconv-liberty-clang:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential gcc g++ clang ccache
    - update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:$PATH"
    - cd liberty
    - CC=clang CXX=clang++ make texconv -j $(nproc)
    - mv texconv texconv-clang
  artifacts:
    paths:
      - liberty/texconv-clang

build-texconv-miami:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential gcc g++ ccache
    - update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:$PATH"
    - cd miami
    - make texconv -j $(nproc)
  artifacts:
    paths:
      - miami/texconv

build-texconv-miami-clang:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential gcc g++ clang ccache
    - update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:$PATH"
    - cd miami
    - CC=clang CXX=clang++ make texconv -j $(nproc)
    - mv texconv texconv-clang
  artifacts:
    paths:
      - miami/texconv-clang

build-sim-liberty:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential gcc g++ libx11-dev ccache
    - update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:$PATH"
    - cd liberty
    - make -f sim.mk -j $(nproc)
  artifacts:
    paths:
      - liberty/dca-liberty-sim.elf

build-sim-liberty-clang:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential gcc g++ libx11-dev clang ccache
    - update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:$PATH"
    - cd liberty
    - CC=clang CXX=clang++ make -f sim.mk -j $(nproc) TARGET=dca-liberty-sim-clang.elf
  artifacts:
    paths:
      - liberty/dca-liberty-sim-clang.elf

build-sim-miami:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential gcc g++ libx11-dev ccache
    - update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:$PATH"
    - cd liberty
    - make -f sim.mk -j $(nproc)
  artifacts:
    paths:
      - liberty/dca-liberty-sim.elf

build-sim-miami-clang:
  variables:
    CCACHE_BASEDIR: $CI_PROJECT_DIR
    CCACHE_DIR: $CI_PROJECT_DIR/ccache
  cache:
    - key: ccache-$CI_JOB_NAME
      paths:
        - $CCACHE_DIR
  stage: build
  before_script:
    - apt update
    - apt install -y build-essential gcc g++ libx11-dev clang ccache
    - update-ccache-symlinks
  script:
    - export PATH="/usr/lib/ccache:$PATH"
    - cd miami
    - CC=clang CXX=clang++ make -f sim.mk -j $(nproc) TARGET=dca-miami-sim-clang.elf
  artifacts:
    paths:
      - miami/dca-miami-sim-clang.elf

pages:
  stage: deploy
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH