CUTS_IFP = \
	A1_ss0.ifp \
	A2_pp.ifp \
	A3_ss.ifp \
	A4_pdr.ifp \
	A5_k2ft.ifp \
	A6_BAIT.ifp \
	A7_ETG.ifp \
	A8_PS.ifp \
	A9_ASD.ifp \
	BET.ifp \
	C1_TEX.ifp \
	D1_STOG.ifp \
	D2_KK.ifp \
	D3_ADO.ifp \
	D4_GTA2.ifp \
	D4_GTA.ifp \
	D5_ES.ifp \
	D6_STS.ifp \
	D7_MLD.ifp \
	el_ph1.ifp \
	el_ph2.ifp \
	el_ph3.ifp \
	el_ph4.ifp \
	END.ifp \
	hd_ph1.ifp \
	hd_ph2.ifp \
	hd_ph3.ifp \
	hd_ph4.ifp \
	hd_ph5.ifp \
	J0_dm2.ifp \
	J1_lfl.ifp \
	J2_kcl.ifp \
	J3_vh.ifp \
	J4_ETH.ifp \
	J5_dst.ifp \
	J6_tbj.ifp \
	JB.ifp \
	k1_kbo.ifp \
	k2_gis.ifp \
	k3_ds.ifp \
	k4_shi2.ifp \
	k4_shi.ifp \
	k5_sd.ifp \
	l1_lg.ifp \
	l2_dsb.ifp \
	l3_dm.ifp \
	l4_pap.ifp \
	l5_tfb.ifp \
	mt_ph1.ifp \
	mt_ph2.ifp \
	mt_ph3.ifp \
	mt_ph4.ifp \
	R0_PDR2.ifp \
	R1_SW.ifp \
	R2_AP.ifp \
	R3_ED.ifp \
	R4_GF.ifp \
	R5_PB.ifp \
	R6_MM.ifp \
	S0_MAS.ifp \
	S1_PF.ifp \
	S2_CTG2.ifp \
	S2_CTG.ifp \
	S3_RTC.ifp \
	S4_BDBA.ifp \
	S4_BDBB.ifp \
	S4_BDBD.ifp \
	S5_LRQb.ifp \
	S5_LRQc.ifp \
	S5_LRQ.ifp \
	t1_tol.ifp \
	t2_tpu.ifp \
	t3_mas.ifp \
	t4_tat.ifp \
	t5_bf.ifp \
	yd_ph1.ifp \
	yd_ph2.ifp \
	yd_ph3.ifp \
	yd_ph4.ifp

CUTS_MISC = \
	a1_ss0_asuka.anm \
	a1_ss0.dat \
	a1_ss0_maria.anm \
	a1_ss0_player.anm \
	a2_pp.dat \
	a2_pp_player.anm \
	a3_ss_asuka.anm \
	a3_ss.dat \
	a3_ss_kenji.anm \
	a3_ss_player.anm \
	a4_pdr_asuka.anm \
	a4_pdr.dat \
	a4_pdr_player.anm \
	a5_k2ft.dat \
	a5_k2ft_player.anm \
	a6_bait_asuka.anm \
	a6_bait.dat \
	a6_bait_player.anm \
	a7_etg_asuka.anm \
	a7_etg.dat \
	a7_etg_player.anm \
	a8_ps_asuka.anm \
	A8_PS.dat \
	a8_ps_maria.anm \
	a8_ps_player.anm \
	a9_asd.dat \
	a9_asd_player.anm \
	bet_cat.anm \
	bet.dat \
	c1_tex_cat.anm \
	c1_tex.dat \
	d1_stog.dat \
	d1_stog_love.anm \
	d1_stog_player.anm \
	D2_KK.dat \
	d2_kk_love.anm \
	d2_kk_player.anm \
	d3_ado.dat \
	d3_ado_love.anm \
	d3_ado_player.anm \
	d4_gta2_asuka.anm \
	d4_gta2_cat.anm \
	d4_gta2.dat \
	d4_gta2_miguel.anm \
	D4_GTA.dat \
	d4_gta_love.anm \
	d4_gta_player.anm \
	d5_es.dat \
	d5_es_love.anm \
	d5_es_player.anm \
	d6_sts.dat \
	d6_sts_love.anm \
	d6_sts_player.anm \
	d7_mld.dat \
	el_ph1.dat \
	el_ph2.dat \
	el_ph3.dat \
	el_ph4.dat \
	end.dat \
	hd_ph1.dat \
	hd_ph2.dat \
	hd_ph3.dat \
	hd_ph4.dat \
	hd_ph5.dat \
	intro.dat \
	J0_dm2.dat \
	j0_dm2_joey.anm \
	j0_dm2_misty.anm \
	j0_dm2_player.anm \
	J1_lfl.dat \
	j1_lfl_joey.anm \
	j1_lfl_misty.anm \
	j1_lfl_player.anm \
	J2_KCL.dat \
	j2_kcl_joey.anm \
	j2_kcl_player.anm \
	j3_vh.dat \
	j3_vh_joey.anm \
	j3_vh_player.anm \
	J4_ETH.dat \
	j4_eth_joey.anm \
	j4_eth_player.anm \
	j4_eth_tony.anm \
	J5_dst.dat \
	j5_dst_joey.anm \
	j5_dst_player.anm \
	j6_tbj.dat \
	j6_tbj_joey.anm \
	j6_tbj_player.anm \
	jb_col1.anm \
	jb.dat \
	K1_KBO.dat \
	k1_kbo_kenji.anm \
	k1_kbo_player.anm \
	K2_GIS.dat \
	k2_gis_kenji.anm \
	k2_gis_player.anm \
	k3_ds.dat \
	k3_ds_kenji.anm \
	k3_ds_player.anm \
	k4_shi2.dat \
	k4_shi2_keeper.anm \
	k4_shi2_player.anm \
	k4_shi.dat \
	k4_shi_kenji.anm \
	k4_shi_player.anm \
	K5_SD.dat \
	k5_sd_kenji.anm \
	k5_sd_player.anm \
	L1_LG.dat \
	l1_lg_eight.anm \
	l1_lg_luigi.anm \
	l1_lg_micky.anm \
	l1_lg_player.anm \
	l2_dsb.dat \
	l2_DSB_micky.anm \
	l2_dsb_player.anm \
	L3_DM.dat \
	l3_dm_luigi.anm \
	l3_dm_micky.anm \
	l3_dm_player.anm \
	l4_pap.dat \
	l4_pap_luigi.anm \
	l4_pap_player.anm \
	L5_TFB.dat \
	l5_tfb_luigi.anm \
	l5_tfb_micky.anm \
	l5_tfb_player.anm \
	mt_ph1.dat \
	mt_ph2.dat \
	mt_ph3.dat \
	mt_ph4.dat \
	R0_PDR2.dat \
	R0_pdr2_player.anm \
	R0_pdr2_ray.anm \
	R1_SW.dat \
	R1_sw_player.anm \
	R1_sw_ray.anm \
	R2_AP.dat \
	R2_ap_player.anm \
	R2_ap_ray.anm \
	r3_ed.dat \
	R3_ed_player.anm \
	R3_ed_ray.anm \
	R4_GF.dat \
	R4_gf_player.anm \
	R4_gf_ray.anm \
	R5_PB.dat \
	R5_pb_player.anm \
	R5_pb_ray.anm \
	R6_MM.dat \
	R6_mm_player.anm \
	R6_mm_ray.anm \
	S0_MAS.dat \
	S0_mas_frank.anm \
	s0_mas_joey.anm \
	s0_mas_luigi.anm \
	s0_mas_player.anm \
	S0_mas_tony.anm \
	S1_PF.dat \
	S1_pf_frank.anm \
	S1_pf_maria.anm \
	S1_pf_player.anm \
	S2_ctg2_cat.anm \
	S2_ctg2_curly.anm \
	s2_ctg2.dat \
	S2_ctg2_miguel.anm \
	S2_CTG.dat \
	s2_ctg_frank.anm \
	S3_rtc.dat \
	S3_rtc_frank.anm \
	S4_BDBA.dat \
	S4_BDBA_eight.anm \
	S4_BDBA_player.anm \
	S4_BDBB.dat \
	S4_BDBB_eight.anm \
	S4_BDBB_player.anm \
	S4_BDBD.dat \
	S5_lrqb_asuka.anm \
	s5_lrqb.dat \
	S5_lrqb_maria.anm \
	S5_lrqc_asuka.anm \
	S5_LRQC.dat \
	S5_lrqc_maria.anm \
	S5_lrqc_player.anm \
	S5_LRQ.dat \
	S5_lrq_frank.anm \
	S5_lrq_player.anm \
	T1_TOL.dat \
	t1_tol_player.anm \
	t1_tol_tony.anm \
	T2_TPU.dat \
	t2_tpu_player.anm \
	T3_MAS.dat \
	t3_mas_player.anm \
	T4_TAT.dat \
	t4_tat_player.anm \
	T5_BF.dat \
	t5_bf_player.anm \
	t5_bf_tony.anm \
	yd_ph1.dat \
	yd_ph2.dat \
	yd_ph3.dat \
	yd_ph4.dat