IMG_MISC = \
  airport.col \
  airportN.col \
  bank.col \
  baseball.ifp \
  biked.ifp \
  bikeh.ifp \
  bikes.ifp \
  bikev.ifp \
  bridge.col \
  buddy.ifp \
  chainsaw.ifp \
  cisland.col \
  CLUB.col \
  coach.ifp \
  colt45.ifp \
  concerth.col \
  docks.col \
  downtown.col \
  downtows.col \
  flame.ifp \
  golf.col \
  grenade.ifp \
  haiti.col \
  haitin.col \
  hotel.col \
  islandsf.col \
  knife.ifp \
  lance.ifp \
  lawyers.col \
  littleha.col \
  m60.ifp \
  mall.col \
  mansion.col \
  medic.ifp \
  nbeachbt.col \
  nbeach.col \
  nbeachw.col \
  oceandN.col \
  oceandrv.col \
  playidles.ifp \
  python.ifp \
  rifle.ifp \
  riot.ifp \
  shotgun.ifp \
  skate.ifp \
  sniper.ifp \
  stadint.col \
  starisl.col \
  stripclb.col \
  strip.ifp \
  sunbathe.ifp \
  sword.ifp \
  tec.ifp \
  uzi.ifp \
  van.ifp \
  washintn.col \
  washints.col \
  yacht.col