IMG_TEXTURES = \
  admiral.txd \
  air_carshow.txd \
  airgrndb.txd \
  airplan.txd \
  airporterminal.txd \
  airport.txd \
  airsignn.txd \
  airstuff2.txd \
  airtrain.txd \
  ak47.txd \
  alleyprop.txd \
  ambulan.txd \
  angel.txd \
  ap_airstuff1.txd \
  ap_billboard.txd \
  apbitsN.txd \
  ap_build1.txd \
  ap_build2.txd \
  ap_build3.txd \
  ap_build4.txd \
  ap_buildings2.txd \
  ap_carpark3.txd \
  apcarparkN.txd \
  ap_checkpoints.txd \
  apchecpointN.txd \
  ap_ci_indus2.txd \
  ap_clothes.txd \
  ap_francisland.txd \
  ap_fuel1.txd \
  ap_fuel2.txd \
  ap_fuel3.txd \
  ap_ground1.txd \
  apgroundN.txd \
  apJumboN.txd \
  ap_jumbos.txd \
  ap_learjets.txd \
  ap_LODbit.txd \
  ap_LOD.txd \
  ap_misc1bit.txd \
  ap_misc1.txd \
  ap_newprops1opac.txd \
  Apoulet.txd \
  ap_roadsect1.txd \
  aproadsN.txd \
  ap_roads.txd \
  ap_runsigns1.txd \
  ap_seaplanprop.txd \
  ap_seasplane.txd \
  ap_terminAint.txd \
  ap_terminal1boards.txd \
  ap_terminal1.txd \
  ap_termwindows.txd \
  ap_viceairport.txd \
  armour.txd \
  army.txd \
  baggage.txd \
  bakstgstuff.txd \
  bank_ext_int.txd \
  banshee.txd \
  barracks.txd \
  barrelexpos.txd \
  barrierm.txd \
  barrier.txd \
  bat.txd \
  bb_barroomtrans.txd \
  bb_barroom.txd \
  bb_exterior.txd \
  beachball.txd \
  bed.txd \
  benches.txd \
  benchm.txd \
  benson.txd \
  bfinject.txd \
  BFOBE.txd \
  bfori.txd \
  bfost.txd \
  bfotr.txd \
  bfybe.txd \
  BFYPR.txd \
  bfyri.txd \
  BFYST.txd \
  bga.txd \
  bgb.txd \
  bilbrd1.txd \
  BillBrd.txd \
  bitcrusher5.txd \
  bka.txd \
  bkb.txd \
  blistac.txd \
  bloodra.txd \
  bloodrb.txd \
  BMOBE.txd \
  bmodk.txd \
  bmost.txd \
  bmotr.txd \
  bmybb.txd \
  bmybe.txd \
  bmybu.txd \
  bmycr.txd \
  bmypi.txd \
  bmyri.txd \
  bmyst.txd \
  bnk_propy.txd \
  boathouse.txd \
  bobcat.txd \
  bomb.txd \
  bonus.txd \
  bounca.txd \
  boxes.txd \
  boxville.txd \
  brassknuckle.txd \
  breifcase.txd \
  brfcase.txd \
  bridge.txd \
  buddyshot.txd \
  buddy.txd \
  buildinghan.txd \
  buildingsite2.txd \
  buildsite.txd \
  buoy.txd \
  burger.txd \
  burrito.txd \
  bustopm.txd \
  bus.txd \
  bwidge.txd \
  cabbie.txd \
  caddy.txd \
  camera.txd \
  canopy.txd \
  carback.txd \
  card.txd \
  carwreck.txd \
  Cba.txd \
  Cbb.txd \
  ccfan.txd \
  cdrivra.txd \
  cdrivrb.txd \
  cellphone.txd \
  centralresac1.txd \
  cgona.txd \
  cgonb.txd \
  cgonc.txd \
  cgoona.txd \
  cgoonb.txd \
  chairsnstufh.txd \
  chairsntable.txd \
  cheetah.txd \
  chef.txd \
  chem2.txd \
  chem.txd \
  chnsaw.txd \
  chopper.txd \
  chromegun.txd \
  ci_backlot.txd \
  ci_ballust.txd \
  ci_dirtcorn.txd \
  ci_filmstuff1.txd \
  ci_industrial.txd \
  ci_island1.txd \
  ci_island3.txd \
  ci_LOD.txd \
  ci_mansion1.txd \
  ci_mansion2.txd \
  ci_mansionint1.txd \
  ci_mansrails.txd \
  ci_pornset.txd \
  ci_posters.txd \
  ci_redhead.txd \
  ci_setstuff1.txd \
  ci_setstuff2.txd \
  ci_setstuff4.txd \
  ci_shadcay.txd \
  ci_shadnit.txd \
  ci_studio1.txd \
  ci_studio2.txd \
  ci_studio3.txd \
  ci_studio4.txd \
  ci_studio5.txd \
  ci_studio6.txd \
  ci_studionew1.txd \
  Cla.txd \
  Clb.txd \
  clchr.txd \
  cleaver.txd \
  cl_ext1.txd \
  cl_ext2.txd \
  cl_ext3.txd \
  cl_vegbits.txd \
  cl_yacht.txd \
  cmraman.txd \
  coach.txd \
  coastg.txd \
  coffeshpext.txd \
  cofintout.txd \
  cofshad.txd \
  cofshopintdet.txd \
  cofshopint.txd \
  cofshopwind.txd \
  coknife.txd \
  colonel.txd \
  colphon.txd \
  colt45.txd \
  coltray.txd \
  comet.txd \
  compound_fence.txd \
  copdoorstuff.txd \
  cop_fake_ext02.txd \
  cop_fake_ext03.txd \
  cop_fake_ext04.txd \
  cop_oceandrv.txd \
  copshop.txd \
  cop.txd \
  corpsedrown.txd \
  courier.txd \
  cpyth.txd \
  craigpackage.txd \
  cranes.txd \
  crate.txd \
  crewa.txd \
  crewb.txd \
  crusher1.txd \
  crusher2.txd \
  crusher3.txd \
  crusherbn.txd \
  crusherb.txd \
  CSAlsb2.txd \
  CSAlscb2.txd \
  CSAlscb.txd \
  CSassA.txd \
  CSassB.txd \
  CSassC.txd \
  CSavery.txd \
  CSbigm.txd \
  CSBJ.txd \
  CSBuddy.txd \
  CScamj.txd \
  cs_cam.txd \
  CSCandy.txd \
  CScgona.txd \
  CScgonb.txd \
  CScgonc.txd \
  cschopb.txd \
  cs_chop.txd \
  CScolo.txd \
  CScougr.txd \
  CSdeal.txd \
  CSdiaz.txd \
  CSDick.txd \
  CSdirec.txd \
  CSdisp.txd \
  CSdlove.txd \
  CSDoris.txd \
  CSdwayn.txd \
  cservra.txd \
  cservrb.txd \
  CSFiller.txd \
  CSganga.txd \
  CSgangb.txd \
  CSgangc.txd \
  CSgona.txd \
  CSgonb.txd \
  CSgonc.txd \
  CSGonz.txd \
  CShlary.txd \
  CSJetro.txd \
  CSJezz.txd \
  CSJuggz.txd \
  CSKelly.txd \
  CSkent.txd \
  CSken.txd \
  CSLance.txd \
  cs_limo.txd \
  CSMaude.txd \
  CSmerc2.txd \
  CSMerc.txd \
  CSmike.txd \
  CSmitch.txd \
  CSpablo.txd \
  CSPapa.txd \
  CSPepe.txd \
  CSPercy.txd \
  CSphil.txd \
  CSplay10.txd \
  CSplay11.txd \
  CSplay2.txd \
  CSplay3.txd \
  CSplay4.txd \
  CSplay5.txd \
  CSplay6.txd \
  CSplay7.txd \
  CSplay8.txd \
  CSplay9.txd \
  CSplay.txd \
  cs_reef.txd \
  CSrich.txd \
  CSsonny.txd \
  CSumbto.txd \
  CSzepp.txd \
  cuban.txd \
  C_worker.txd \
  dcfan.txd \
  deaddodo.txd \
  deagl.txd \
  delcase.txd \
  deliext.txd \
  deliint.txd \
  deluxo.txd \
  destructo.txd \
  dgoona.txd \
  dgoonb.txd \
  dgoonc.txd \
  diaz.txd \
  dinghy.txd \
  dkcargoshp.txd \
  dkglue.txd \
  dk_houses.txd \
  dk_midbuilds.txd \
  dk_safecrack.txd \
  doccrane.txd \
  docentrance.txd \
  docfactories.txd \
  dock_bridge.txd \
  dockfence.txd \
  dockgrass.txd \
  dockgrnd.txd \
  docklight.txd \
  dockroads.txd \
  docksb.txd \
  dock_ships.txd \
  dock_shipsunder.txd \
  docks.txd \
  dolphin.txd \
  drchair.txd \
  drink.txd \
  drubish.txd \
  drugfactint.txd \
  drugpak.txd \
  drycleaners.txd \
  dshotgn.txd \
  dt_ammu3.txd \
  dt_ammu.txd \
  dt_blimp.txd \
  dt_bloodring.txd \
  dt_bluebuild.txd \
  dt_bridges.txd \
  dt_brij_LOD.txd \
  dt_compoundroof.txd \
  dt_cube_build.txd \
  dt_CUNT2.txd \
  dt_CUNT.txd \
  dt_dirtrng.txd \
  dt_egg1.txd \
  dt_firestation2.txd \
  dt_firestation.txd \
  dt_hole_build.txd \
  dt_hospital.txd \
  dt_hotring.txd \
  dt_lites.txd \
  dt_LOD2.txd \
  dt_LOD.txd \
  dt_modern1.txd \
  dt_modern2.txd \
  dt_nbeach.txd \
  dtn_cables2.txd \
  dtn_cables.txd \
  dt_newtest1.txd \
  dt_newtest2.txd \
  dtn_ground2.txd \
  dtn_ground.txd \
  dtn_roads.txd \
  dt_ntrack.txd \
  dtn_veg.txd \
  dt_qbert.txd \
  dts_bikebar_ext.txd \
  dts_copshop.txd \
  dt_scyscrap2.txd \
  dts_grassbits.txd \
  dts_ground.txd \
  dt_sheraton.txd \
  dt_shops130.txd \
  dt_shops13.txd \
  dt_shops14.txd \
  dt_shops180.txd \
  dt_shops182.txd \
  dt_shops188.txd \
  dt_shops18.txd \
  dt_shops1.txd \
  dt_shops2.txd \
  dt_shops3.txd \
  dt_shops5.txd \
  dt_shops6.txd \
  dt_shops.txd \
  dts_LODbig.txd \
  dts_LODsmall2.txd \
  dts_LODsmall.txd \
  dts_nbeach.txd \
  dts_nitelites.txd \
  dts_office.txd \
  dts_roads.txd \
  dts_shops1.txd \
  dts_shops_new1.txd \
  dts_shops.txd \
  dt_stadium.txd \
  dt_tall_build01.txd \
  dt_topshops1100.txd \
  dt_topshops130.txd \
  dt_topshops1.txd \
  dt_topshops4.txd \
  dt_topshops50.txd \
  dt_topshops5.txd \
  dt_topshops6.txd \
  dt_topshops.txd \
  dt_VCnews.txd \
  dynamite.txd \
  dynbarrels.txd \
  dynbuket.txd \
  dyncones.txd \
  dyn_drugs.txd \
  dynhydrent.txd \
  dynjunk.txd \
  dyn_keycard.txd \
  dynnewstnd2.txd \
  dynnewstnd.txd \
  dynphnm.txd \
  dynphn.txd \
  dynpostbx.txd \
  dynrecycle.txd \
  dynsigns.txd \
  dyntraffic.txd \
  dyn_trash.txd \
  dzplant.txd \
  electricgate.txd \
  enforcer.txd \
  escstep.txd \
  esperant.txd \
  espreso.txd \
  expltrk.txd \
  faggio.txd \
  fanani.txd \
  fbicar.txd \
  fbiranch.txd \
  fbi.txd \
  fencehaiti.txd \
  fences.txd \
  fffinhaiti.txd \
  fingers.txd \
  fireman.txd \
  firem.txd \
  firetruk.txd \
  fish1.txd \
  fish2.txd \
  fish3.txd \
  flame.txd \
  flatbedbak.txd \
  flatbed.txd \
  floozya.txd \
  floozyb.txd \
  floozyc.txd \
  foodcourt.txd \
  freeway.txd \
  FSfa.txd \
  fuckedcarlh.txd \
  funhiati.txd \
  gangb.txd \
  gangbur.txd \
  gangshop.txd \
  gasgren.txd \
  gcfan.txd \
  Gda.txd \
  Gdb.txd \
  Generic.txd \
  gfflag.txd \
  gf_hedge1.txd \
  gf_LOD.txd \
  gf_nbtecland.txd \
  gf_northbridge.txd \
  gfnorthisland3.txd \
  gfpalms.txd \
  gf_roadblock.txd \
  gfwater.txd \
  glendale.txd \
  golf3.txd \
  golf_bridge.txd \
  golf_clubhouse1.txd \
  golf_clubhouse2.txd \
  golfclub.txd \
  gpass.txd \
  grasspatch.txd \
  greenwoo.txd \
  grenade.txd \
  gtatrees.txd \
  guesta.txd \
  guestb.txd \
  guestc.txd \
  guestd.txd \
  gunbox.txd \
  guncolt.txd \
  habuildblok.txd \
  hahospital.txd \
  hai_carshowint.txd \
  hai_hoj.txd \
  haitbuild41.txd \
  haitbuildb.txd \
  haitbuildsea1.txd \
  haitbuildsea2.txd \
  haitcontext.txd \
  haitcont.txd \
  haitiblk1sj.txd \
  haitinwire.txd \
  haitisig.txd \
  haititag.txd \
  haitplntn.txd \
  haitplnt.txd \
  haitrdbuilf.txd \
  haiwash.txd \
  hammer.txd \
  hatrifl.txd \
  havbasketball.txd \
  hav_health.txd \
  hav_police.txd \
  helipad.txd \
  helixbarrier.txd \
  hermes.txd \
  hfobe.txd \
  hfori.txd \
  HFOST.txd \
  HFOTR.txd \
  hfybe.txd \
  HFYBU.txd \
  HFYCG.txd \
  HFYMD.txd \
  HFYPR.txd \
  HFYRI.txd \
  HFYST.txd \
  h_haibloce.txd \
  hi_cutbnk_alp.txd \
  hi_cutbnkchr.txd \
  hi_cutbnkcoch.txd \
  hi_cutbnkmain3.txd \
  hi_cutbnkmainnw.txd \
  hi_cutbnkrecpt.txd \
  hi_cutbnkvault.txd \
  hi_cutclof_opa.txd \
  hi_cutclubbar.txd \
  hi_cutcluboffice.txd \
  hi_cutclwaltst.txd \
  hi_cutcouch.txd \
  hi_cuthoomintshad.txd \
  hi_cuthotel1.txd \
  hi_cuthtl2.txd \
  hi_cuthtl4.txd \
  hi_cuthtlalp.txd \
  hi_cutint1.txd \
  hi_cutintprops.txd \
  hi_cutlaw1.txd \
  hi_cutlaw2.txd \
  hi_cutlaw3b.txd \
  hi_cutlaw3c.txd \
  hi_cutlaw3.txd \
  hi_cutlawshad.txd \
  hi_cutmaincl.txd \
  hi_cutmanshad.txd \
  hi_cutmngof.txd \
  hi_cutpropy.txd \
  hi_cutrshad.txd \
  hi_cutsafehoos.txd \
  hi_cutsafe.txd \
  hi_cutsdrm_1.txd \
  hi_cutsdrm_2.txd \
  hi_cutsdrm_3.txd \
  hi_cuttblprop.txd \
  hlrycar.txd \
  hmobe.txd \
  hmoca.txd \
  hmori.txd \
  hmost.txd \
  hmotr.txd \
  hmyap.txd \
  hmybe.txd \
  hmyri.txd \
  hmyst.txd \
  Hna.txd \
  Hnb.txd \
  hotelroomint2.txd \
  hotelroomint.txd \
  hot_mobint.txd \
  hotrina.txd \
  hotrinb.txd \
  hotring.txd \
  hot_roomtrans.txd \
  htable.txd \
  htdoorhtlalp.txd \
  htl_ext03.txd \
  htlpoolbase.txd \
  hunter.txd \
  icons1.txd \
  icons2.txd \
  icons3.txd \
  icons4.txd \
  icons5.txd \
  icons6.txd \
  icons7.txd \
  icons8.txd \
  icons9.txd \
  icons.txd \
  idaho.txd \
  IGalscb.txd \
  IGbuddy.txd \
  IGBudy2.txd \
  IGBudy3.txd \
  IGCandy.txd \
  IGColon.txd \
  IGDiaz.txd \
  IGDick.txd \
  IGGonz.txd \
  IGHlary.txd \
  IGHlry2.txd \
  IGJezz.txd \
  IGKen.txd \
  IGMerc2.txd \
  IGMerc.txd \
  IGMike2.txd \
  IGmike.txd \
  IGPercy.txd \
  IGphil2.txd \
  IGPhil3.txd \
  IGPhil.txd \
  IGSonny.txd \
  ihaitcutmf.txd \
  ihsnidxc.txd \
  infernus.txd \
  ingramsl.txd \
  intstairod.txd \
  invite.txd \
  islandlolodb.txd \
  islandlolodm.txd \
  islandmanext1.txd \
  jellyfish1.txd \
  jellyfish2.txd \
  jetmax.txd \
  jfoto.txd \
  jmoto.txd \
  jumpbox.txd \
  junk.txd \
  jwcoffin.txd \
  jwlr.txd \
  jzgirla.txd \
  jzgirlb.txd \
  katana.txd \
  kaufman.txd \
  kentpaul.txd \
  kettle.txd \
  KgoonA.txd \
  KgoonB.txd \
  kickstart.txd \
  knifecur.txd \
  landjump.txd \
  landstal.txd \
  laser.txd \
  lawcutext.txd \
  lawdoor.txd \
  lawyer.txd \
  lcfan.txd \
  lf_mediastage.txd \
  lhaith9.txd \
  lhaiths.txd \
  lhaithutn.txd \
  lhaitiblk1fg.txd \
  lhaitiblk2.txd \
  lhaitiblk4sj.txd \
  lhaitiblk6f.txd \
  lhaitiblk6k.txd \
  lhaitiblkhuty.txd \
  lhaitiblkplat.txd \
  lhaitiblkplt2.txd \
  lhaitiblksick.txd \
  lhalleysect.txd \
  lhbillbrd.txd \
  lhblbrd2.txd \
  lhblbrd3.txd \
  lhblbrd8.txd \
  lhbuild3.txd \
  lhcabbyext.txd \
  lhcabby.txd \
  lh_dockstuff1.txd \
  lh_dockstuffN1.txd \
  lhfuckercars.txd \
  lhgangshop.txd \
  lh_garagebits.txd \
  lhgardens.txd \
  lhglue.txd \
  lh_haibljki.txd \
  lh_haiblockc1.txd \
  lh_haiblockc2.txd \
  lhhotelbg.txd \
  lh_imp_exp1.txd \
  lh_imp_exp2.txd \
  lh_imp_exp3.txd \
  lh_imp_exp4.txd \
  lhjetty.txd \
  lhmachine1mn.txd \
  lhmachine1m.txd \
  lhparkline.txd \
  lh_PWbuild1grnd.txd \
  lh_PWbuild1.txd \
  lh_PWbuild2.txd \
  lh_PWbuild3.txd \
  LH_PWInterior2.txd \
  LH_PWInterior.txd \
  lhrace1.txd \
  lhrace2.txd \
  lhrace3.txd \
  lhrace4.txd \
  lhrace5.txd \
  lhrace6.txd \
  lh_racemap.txd \
  lhroadsign.txd \
  lh_roads.txd \
  lhrooft2.txd \
  lhrooft.txd \
  lh_taxi.txd \
  linerun.txd \
  lithablk12.txd \
  lithablk22.txd \
  lithablk4.txd \
  lithablk9.txd \
  lithahotel.txd \
  lithahouse.txd \
  lithawaste.txd \
  litthabg1.txd \
  litthablk6.txd \
  littlehab2.txd \
  littlhab1.txd \
  littlhablk7.txd \
  lobster.txd \
  lobtray.txd \
  LODairpN.txd \
  LODbridge.txd \
  LODbuildws07.txd \
  lod_docks2.txd \
  lod_docks.txd \
  LODhaitibig.txd \
  LODhaitinbig.txd \
  LODhaitin.txd \
  LODhaiti.txd \
  LODhavanabrg.txd \
  LODhavana.txd \
  lodhavbig.txd \
  lod_mall.txd \
  lod_man_grnds.txd \
  LODnbchw.txd \
  LODnbeachbtbig.txd \
  LODnbeach.txd \
  LODnbeachwbig.txd \
  LODodriveN.txd \
  LODodrive.txd \
  lod_starbig.txd \
  lod_starsmall.txd \
  LODwashnbrdge.txd \
  LODwashsth.txd \
  LODwshsth99.txd \
  LODwsouth08.txd \
  LODxrefhot.txd \
  lofbanner.txd \
  lounger.txd \
  lovefist.txd \
  luggage.txd \
  lwchara.txd \
  lwcharb.txd \
  m4.txd \
  m60.txd \
  machete.txd \
  mainclub2.txd \
  male01.txd \
  mall_ammu.txd \
  mallcarpark.txd \
  mallext.txd \
  mall_ground.txd \
  mallitems.txd \
  mallplants.txd \
  mall_props.txd \
  mallroof.txd \
  malltotal.txd \
  mall_veg.txd \
  manana.txd \
  manbackside.txd \
  man_cellar.txd \
  manf.txd \
  man_grnds_kb.txd \
  man_hall_2.txd \
  man_hall.txd \
  mannewdoors.txd \
  man_pool1.txd \
  man_pool2.txd \
  man_pool_shado.txd \
  man_props.txd \
  man_scarface.txd \
  mansion_details2.txd \
  mansion_details.txd \
  mansiondoor.txd \
  mansionfence.txd \
  mansion_new.txd \
  mansion_Rubbish.txd \
  mansionwall.txd \
  man_twr.txd \
  man_veg_ext.txd \
  man_wtr_ftr.txd \
  marinacpark.txd \
  marquis.txd \
  maverick.txd \
  Mba.txd \
  Mbb.txd \
  mbtbemp.txd \
  mbtbful.txd \
  mcane.txd \
  mcompounda1.txd \
  medic.txd \
  merced.txd \
  mesa.txd \
  metal.txd \
  mfour.txd \
  mgoona.txd \
  miamibin.txd \
  militcompound3.txd \
  mine.txd \
  minigun2.txd \
  minigun.txd \
  missile.txd \
  mitraffic.txd \
  ml_books.txd \
  ml_clothes.txd \
  ml_coffee.txd \
  ml_jewellers.txd \
  ml_tuneless.txd \
  molotov.txd \
  moonbeam.txd \
  mp5lng.txd \
  mpfshrt.txd \
  mporna.txd \
  mrwhoop.txd \
  mserver.txd \
  mule.txd \
  nairport.txd \
  nb_bridge1.txd \
  nbchbtjetty.txd \
  nbchdrtrack.txd \
  nbchflw.txd \
  nbdcprmndfnc.txd \
  nbdecopromnd.txd \
  nbdecoshop01.txd \
  nbdecoshop02.txd \
  nbdecoshop03.txd \
  nbeachbit03rails.txd \
  nbeachbridge.txd \
  nbeachgen.txd \
  nbeach_lod.txd \
  nbeachneon.txd \
  nbeachpayns.txd \
  nbeachrdsign.txd \
  nbeachwgen.txd \
  nbecbtwbrdge.txd \
  nbecdiving.txd \
  nbecland12bball.txd \
  nbecland12gates.txd \
  nbglue.txd \
  nbhospital.txd \
  nbhotel01.txd \
  nbhotel02.txd \
  nbhotel03.txd \
  nbhotel04.txd \
  nbhotel05.txd \
  nbhotel06.txd \
  nbhotel07.txd \
  nbhotel08.txd \
  nb_police.txd \
  nbrooft.txd \
  nbsavehotel.txd \
  nbt_apartpool01.txd \
  nbt_apartpool.txd \
  nbt_barfence01.txd \
  nbtecland.txd \
  nbt_hotel01.txd \
  nbt_hotel02.txd \
  nbt_hotel03glass.txd \
  nbt_hotel03.txd \
  nbt_hotel04.txd \
  nbt_hotel05.txd \
  nbt_hotel06balcony.txd \
  nbt_hotel06.txd \
  nbt_hotel07fence.txd \
  nbt_hotel07.txd \
  nbthotel08fence.txd \
  nbthotel08.txd \
  nbt_htlpoolbar01.txd \
  nbt_htlpoolbase.txd \
  nbt_htlpoolrm.txd \
  nbt_mans04balcony.txd \
  nbt_mansion01.txd \
  nbt_mansion02.txd \
  nbt_mansion03.txd \
  nbt_mansion04.txd \
  nbt_mansionbase01.txd \
  nbt_mansionbase02.txd \
  nbt_mnsnwtr.txd \
  nbt_pizzaplace.txd \
  nbtroofnext.txd \
  nbtrooftop.txd \
  nbtshopfronts02.txd \
  nbtshops.txd \
  nbtsmallres.txd \
  nbwbridge.txd \
  nbw_grssypatch.txd \
  nbw_hotel06balcony.txd \
  nbw_hotel06.txd \
  nbwjetty.txd \
  nbw_pinkblock.txd \
  nbwtoolshp5.txd \
  ncarwreck.txd \
  neonnd.txd \
  newashbuild1.txd \
  newbuilding01.txd \
  newrampn.txd \
  newramp.txd \
  newroof.txd \
  newspadbuild.txd \
  newstand.txd \
  nitestick.txd \
  northbuild.txd \
  nubuilding1glass.txd \
  oceanic.txd \
  oceanstrip10.txd \
  oceanstrip2.txd \
  ocmiamistrip12.txd \
  ocmiamistrip16.txd \
  ocmiamistrip5.txd \
  ocmiamistrip6.txd \
  ocmiamistrip7.txd \
  ocmiamistrip8.txd \
  ocmiamistrip9.txd \
  ocmiamistrip9X.txd \
  ocmiamistrip.txd \
  ocnmiamistrip.txd \
  od_beachstuff.txd \
  od_bighotel.txd \
  od_bighotpool.txd \
  od_bigshops2.txd \
  od_bphq.txd \
  od_chariot.txd \
  od_clubback.txd \
  od_clubout.txd \
  od_cop_interior.txd \
  od_fence.txd \
  od_hotels1.txd \
  od_lighthousein.txd \
  od_lighthouse.txd \
  od_neons1.txd \
  odneontest.txd \
  odnglue.txd \
  odnhotelblk.txd \
  odnhotelspr.txd \
  odnroads.txd \
  odnrooft.txd \
  odnwire.txd \
  od_watertower.txd \
  od_waterwrx.txd \
  package1.txd \
  packer.txd \
  patriot.txd \
  pcj600.txd \
  peren.txd \
  petrolcan.txd \
  petrol.txd \
  Pga.txd \
  Pgb.txd \
  pharmacyint.txd \
  pheonix.txd \
  philbmb.txd \
  philinter.txd \
  philss.txd \
  phnplay.txd \
  phoncol.txd \
  pitchrb.txd \
  pizzaboy.txd \
  play10.txd \
  play11.txd \
  play12.txd \
  player2.txd \
  player3.txd \
  player4.txd \
  player5.txd \
  player6.txd \
  player7.txd \
  player8.txd \
  player9.txd \
  player.txd \
  plc_stinger.txd \
  plyphon.txd \
  polbals.txd \
  policechair.txd \
  police.txd \
  polmav.txd \
  pony.txd \
  poolcue.txd \
  poolq.txd \
  portabarrier.txd \
  predator.txd \
  printra.txd \
  printrb.txd \
  printrc.txd \
  propbarstuff.txd \
  prop_pizzabox.txd \
  psycho.txd \
  python.txd \
  radar00.txd \
  radar01.txd \
  radar02.txd \
  radar03.txd \
  radar04.txd \
  radar05.txd \
  radar06.txd \
  radar07.txd \
  radar08.txd \
  radar09.txd \
  radar10.txd \
  radar11.txd \
  radar12.txd \
  radar13.txd \
  radar14.txd \
  radar15.txd \
  radar16.txd \
  radar17.txd \
  radar18.txd \
  radar19.txd \
  radar20.txd \
  radar21.txd \
  radar22.txd \
  radar23.txd \
  radar24.txd \
  radar25.txd \
  radar26.txd \
  radar27.txd \
  radar28.txd \
  radar29.txd \
  radar30.txd \
  radar31.txd \
  radar32.txd \
  radar33.txd \
  radar34.txd \
  radar35.txd \
  radar36.txd \
  radar37.txd \
  radar38.txd \
  radar39.txd \
  radar40.txd \
  radar41.txd \
  radar42.txd \
  radar43.txd \
  radar44.txd \
  radar45.txd \
  radar46.txd \
  radar47.txd \
  radar48.txd \
  radar49.txd \
  radar50.txd \
  radar51.txd \
  radar52.txd \
  radar53.txd \
  radar54.txd \
  radar55.txd \
  radar56.txd \
  radar57.txd \
  radar58.txd \
  radar59.txd \
  radar60.txd \
  radar61.txd \
  radar62.txd \
  radar63.txd \
  rafneonsign.txd \
  ramp2.txd \
  rancher.txd \
  rcbandit.txd \
  rcbaron.txd \
  rcbomb.txd \
  rcgoblin.txd \
  rcraider.txd \
  recstudio2.txd \
  recstudio.txd \
  reefer.txd \
  regina.txd \
  rhino.txd \
  rio.txd \
  roadsign.txd \
  rocketla.txd \
  rock.txd \
  rocky.txd \
  romero.txd \
  roofbit.txd \
  ruger.txd \
  rumpo.txd \
  sabretur.txd \
  sabre.txd \
  sam.txd \
  sanchez.txd \
  sandcastle.txd \
  sandking.txd \
  satdish.txd \
  scarinterior.txd \
  scenery.txd \
  schair.txd \
  screwdriver.txd \
  seabed.txd \
  seaspar.txd \
  securica.txd \
  sentinel.txd \
  sentxs.txd \
  seveneleven.txd \
  sfrenda.txd \
  sfrendb.txd \
  Sga.txd \
  Sgb.txd \
  sgc.txd \
  sgoona.txd \
  sgoonb.txd \
  sharedalleyod.txd \
  shared_beach.txd \
  sharedbiggrass.txd \
  shark.txd \
  shipthisgamenow.txd \
  shootra.txd \
  shootrb.txd \
  shopfronts03.txd \
  shotgspa.txd \
  shotvcr.txd \
  signs.txd \
  sjmahaitiground.txd \
  sjmbncrusher5.txd \
  sjmh1haitiroad.txd \
  sjmh5haitiroad.txd \
  sjmhahaitiground.txd \
  sjmhbghaitiground.txd \
  sjmjcrusher4.txd \
  sjmroadhaitiN.txd \
  sjmsprayn.txd \
  sjmspray.txd \
  S_keep.txd \
  skimmer.txd \
  smashbarr.txd \
  sniper.txd \
  spad_buildnew.txd \
  spad_main.txd \
  spad_opac.txd \
  spad_shado.txd \
  spad_water.txd \
  spand.txd \
  spandxa.txd \
  spandxb.txd \
  sparrow.txd \
  speeder.txd \
  speed.txd \
  squalo.txd \
  ssjmcrusher5.txd \
  stagebar.txd \
  stagestuff.txd \
  stallion.txd \
  standext.txd \
  sta_pinkblock.txd \
  star1b.txd \
  star1.txd \
  star2.txd \
  star3.txd \
  star4.txd \
  star5.txd \
  starbits06.txd \
  starbits17.txd \
  starbits22.txd \
  starbits24.txd \
  starbits49.txd \
  starbits50.txd \
  starbits51.txd \
  starbridge.txd \
  starbuildsite.txd \
  stardepot.txd \
  starf.txd \
  StarLD.txd \
  starmansionst.txd \
  starpool.txd \
  starroad.txd \
  starvillas01.txd \
  starwaterfrnt01.txd \
  stilty.txd \
  stinger.txd \
  stmansion.txd \
  streetlights.txd \
  stretch.txd \
  Stripa.txd \
  stripback.txd \
  stripb.txd \
  stripc.txd \
  stripinter.txd \
  striplights.txd \
  strpclbsgns.txd \
  stunt.txd \
  subcrates.txd \
  submarine.txd \
  svntray.txd \
  swashlandb.txd \
  swashnwbuild5.txd \
  swat.txd \
  swimupbar.txd \
  swshneon.txd \
  swshtelgrph.txd \
  targets.txd \
  taxi_d.txd \
  taxi.txd \
  teargas.txd \
  tec9.txd \
  telegraph.txd \
  telephait.txd \
  telly.txd \
  tikiprops01.txd \
  tit_wank.txd \
  topfun.txd \
  towerdoor.txd \
  transbits2.txd \
  trash.txd \
  treeshad.txd \
  tropic.txd \
  tunnel.txd \
  turtle.txd \
  uzi.txd \
  vcnmav.txd \
  vegetation.txd \
  vend.txd \
  vice1.txd \
  vice2.txd \
  vice3.txd \
  vice4.txd \
  vice5.txd \
  vice6.txd \
  vice7.txd \
  vice8.txd \
  vicechee.txd \
  virgo.txd \
  voodoo.txd \
  walton.txd \
  wash_ammu.txd \
  washbballcrt.txd \
  washbuild120.txd \
  washbuild124.txd \
  washbuild13.txd \
  washbuild15.txd \
  washbuild1.txd \
  washbuild41.txd \
  washbuild43.txd \
  washbuild44.txd \
  washbuild5.txd \
  washbuild6.txd \
  washbuild7.txd \
  washcorn2.txd \
  washcpark2.txd \
  washfence128.txd \
  wash_hosp.txd \
  washing.txd \
  washlandb.txd \
  washland.txd \
  washmallnew.txd \
  washmallpark.txd \
  washmarina.txd \
  washmiamistrip11.txd \
  washmiamistrip13.txd \
  washmiamistrip2.txd \
  washmiamistrip3.txd \
  washmiamistrip4.txd \
  washnewbuild1.txd \
  washnewbuild21.txd \
  washnewbuild23.txd \
  washnewbuild24.txd \
  washnewbuild25.txd \
  washnewbuild2.txd \
  washnewbuild3.txd \
  washnewbuild5.txd \
  washnewbuild6.txd \
  washnrthpstr1.txd \
  washotel2.txd \
  washrestone.txd \
  washroads.txd \
  washsfehse.txd \
  washshops1.txd \
  washsky1.txd \
  washsthpstr.txd \
  washwater.txd \
  wastebin.txd \
  wa_tool2.txd \
  wfobe.txd \
  wfogo.txd \
  wfori.txd \
  wfosh.txd \
  wfost.txd \
  wfotr.txd \
  wfybe.txd \
  wfybu.txd \
  wfycst.txd \
  wfyg1.txd \
  wfyg2.txd \
  wfyjg.txd \
  WFYLG.txd \
  wfypr.txd \
  wfyri.txd \
  wfysh.txd \
  wfysk.txd \
  wfyst.txd \
  wglass.txd \
  wire.txd \
  wmobe.txd \
  wmobu.txd \
  wmoca.txd \
  wmogo.txd \
  wmori.txd \
  wmost.txd \
  wmotr.txd \
  wmybe.txd \
  wmybu.txd \
  wmycr.txd \
  wmycw.txd \
  wmygo.txd \
  wmyjg.txd \
  WMYLG.txd \
  wmypi.txd \
  wmyri.txd \
  wmysk.txd \
  wmyst.txd \
  woodpanels.txd \
  woshmalglas.txd \
  wshbuildirt.txd \
  wshbuildws40.txd \
  wshcoklnd.txd \
  wshcrprkdrt.txd \
  wshcrprkstuf.txd \
  wshgarage1.txd \
  wshmolmrk.txd \
  wshneon.txd \
  wshotelsign35.txd \
  wshrdblck.txd \
  wshsprayshp.txd \
  wshsthbuild1.txd \
  wshstripint.txd \
  wshtelgrph.txd \
  wshxrefhirise.txd \
  wshxrefhse2.txd \
  wshxrefhse.txd \
  wshxreflod.txd \
  wshxrefpump.txd \
  wslawyers.txd \
  xrefhotels.txd \
  yacht_kb.txd \
  yacht_lod.txd \
  yachttings.txd \
  yacht.txd \
  yankee.txd \
  yt_launch.txd \
  zebra.txd